- src/app/register/page.tsx
- src/app/upload/page.tsx
- src/component/MenuBar.tsx
- src/style/_util.scss
- src/style/menubar.scss
- src/style/register.scss
- src/style/upload.scss
- src/style/weatherBar.scss
> #11 회원가입 수정 완료

- src/app/feed/page.tsx
- src/component/WeatherBar.tsx
> [Feat]weather_req (#10)

- src/app/feed/page.tsx
- src/app/login/page.tsx
> [Fix]loginpage

- src/app/feed/page.tsx
- src/app/login/page.tsx
- src/app/register/page.tsx
- src/app/upload/page.tsx
- src/component/MenuBar.tsx
- src/component/WeatherBar.tsx
- src/style/_util.scss
- src/style/menubar.scss
- src/style/register.scss
- src/style/upload.scss
- src/style/weatherBar.scss
> [Feat]weather_req(#10)

- src/app/login/page.tsx
- src/app/mypage/page.tsx
- src/component/LikePost.tsx
- src/component/MyPost.tsx
- src/style/mypage.scss
> login test

- src/app/upload/page.tsx
- src/component/ImageUpload.tsx
- src/component/MenuBar.tsx
- src/style/upload.scss
- 서버 연결 완료
- 업로드 기능 완료
- 디자인은 아직 수정 필요
> [Feat] 업로드 페이지 기능 구현 완료

- src/app/login/page.tsx
- src/app/mypage/page.tsx
- src/component/LikePost.tsx
- src/component/MyPost.tsx
- src/component/Profile.tsx
- src/component/ProfileModal.tsx
- src/component/TabBar.tsx
- src/style/mypage.scss
- 마이페이지 탭 기능 추가
- 마이페이지 정보 수정 모달 제작 ing........
> [feat] #32 mypage function

- src/app/login/page.tsx
> [Fix] 로그인 axios 수정 #32

- src/component/FeedContents.tsx
- src/component/FeedSearch.tsx
> 서버 연결 확인 테스트

- src/app/login/page.tsx
- src/app/register/page.tsx
- src/app/socialregister/page.tsx
- src/app/upload/page.tsx
- src/style/detail.scss
- import 코드 수정
- 구글 로그인 기능 구현중
- 웨더바 표시 방식 수정
> [Fix] 구글 로그인 기능 및 웨더바 표시 #34 

- next.config.js
- src/app/detail/page.tsx
- src/component/Comment.tsx
- src/component/CommentModal.tsx
- src/component/Comments.tsx
- src/component/ContentDetail.tsx
- src/component/ImageDetail.tsx
- src/component/Like.tsx
- src/component/Profile.tsx
- 닉네임, 이미지, 글 불러와짐
- 해시태그, 여러 이미지 확인 필요
> [Feat] #56 게시물 상세 페이지 - 데이터 불러오기

- src/app/detail/page.tsx
[Fix]빌드 에러 수정(upload, detail, feed)
> [Fix]빌드 에러 수정(upload, detail, feed)

- src/app/detail/page.tsx
- src/app/feed/page.tsx
- src/app/layout.tsx
- src/app/login/page.tsx
- src/app/main/page.tsx
- src/app/upload/page.tsx
- src/component/LoginForm.tsx
- src/component/RecoilRootProvider.tsx
라우터로 지정해줘야 데이터가 유지됨..ㅠㅠ 이걸 몰라서 1시간 버리다니..
수치다...
> [Fix] 리코일 적용 #33

- src/app/page.tsx
> [Feat] 로그인 토큰 유지 로직 개발중 #73

- src/component/LoginForm.tsx
> [Feat] 로그인 하자마자 쿠기에 토큰 들어옴 #73

- src/component/LoginForm.tsx
> [Feat] 로그인 하자마자 쿠기에 토큰 들어옴

- src/app/register/page.tsx
- src/component/FeedCateDetail.tsx
- src/component/FeedContents.tsx
- src/component/FeedSearch.tsx
- src/component/LoginForm.tsx
> [Fix] Feed페이지 수정 (#10)

- src/app/mypage/page.tsx
- src/component/LoginForm.tsx
[Feat]로그인 토큰 존재할떄만 마이페이지 랜더링 (#9)
> [Feat]로그인 토큰 존재할떄만 마이페이지 랜더링 (#9)

- .env
- src/app/layout.tsx
- src/app/mypage/page.tsx
- src/app/socialregister/page.tsx
- src/component/GoogleProvider.tsx
- src/component/LoginForm.tsx
- src/component/NextAuth.ts
[Feat] 소셜 로그인 토큰 백으로 보내기 (#34)
> [Feat] 소셜 로그인 토큰 백으로 보내기 (#34)

- next.config.js
- src/app/detail/edit/page.tsx
- src/app/detail/page.tsx
- src/app/upload/page.tsx
- src/component/ImageUpload.tsx
- 업로드 페이지: 카테고리 선택 안되는 오류 수정
- 수정 페이지: 이미지 안 불러와지는 오류 수정
> [Fix] #8, #56 게시물 업로드 및 수정 페이지 기능 오류 수정

- src/app/mypage/page.tsx
- src/app/register/page.tsx
- src/app/socialregister/page.tsx
- src/app/upload/page.tsx
- src/component/FeedContents.tsx
- src/component/InputBar.tsx
- src/component/LoginForm.tsx
- src/recoilAtom/Login_token.ts
> [Feat] 로그인 토큰 전역 관리

- next.config.js
- src/app/detail/page.tsx
- src/app/register/page.tsx
- src/app/socialregister/page.tsx
- src/app/upload/page.tsx
- src/component/FeedContents.tsx
- src/component/LoginForm.tsx
- src/component/WeatherBar.tsx
- src/recoilAtom/FeedBoardId.ts
- src/recoilAtom/FeedContents.ts
- src/style/register.scss
[Feat] 로그인 전역 관리 완료, 피드 아이콘 추가, 업로드 아이콘 보내기(#10)
> [Feat] 로그인 전역 관리 완료, 피드 아이콘 추가, 업로드 아이콘 보내기(#10)

- src/app/feed/page.tsx
- src/component/FeedCateDetail.tsx
- src/component/FeedCategory.tsx
- src/component/FeedContents.tsx
- src/component/FeedSearch.tsx
- src/component/LoginForm.tsx
- src/component/MainWeather.tsx
- src/recoilAtom/FeedContents.ts
- src/recoilAtom/FeedLoginToken.ts
- src/recoilAtom/FeedNickname.ts
- src/style/feedContent.scss
> [Feat]피드페이지 좋아요 기능 (#10)

- src/app/detail/page.tsx
- src/component/CommentIcon.tsx
- src/component/CommentTest.tsx
- src/component/FeedContents.tsx
- src/component/Like.tsx
> [Feat] 좋아요 기능 피드페이지 디테일 페이지 구현 완료(#10)

- src/app/detail/edit/page.tsx
Reverts kdt-8-4/weatherfit-frontend#123
> [Fix] #56 이미지 업로드 기능 수정:re

- src/app/mypage/page.tsx
- src/component/CommentTest.tsx
- src/component/LikePost.tsx
- src/component/MyPost.tsx
- src/component/MypageProfile.tsx
- src/component/ProfileModal.tsx
- src/component/ProfileModalTest.tsx
- src/component/TabBar.tsx
- src/style/modal_comment.scss
> [fix] 마이페이지 수정 중

- src/app/detail/edit/page.tsx
- src/app/detail/page.tsx
- src/component/BestItem.tsx
- src/component/ImageUpload.tsx
- src/component/Like.tsx
- src/component/MainWeather.tsx
- src/recoilAtom/WeatherState.ts
- 이미지 업로드 기능 수정
- 게시글 수정 페이지 기능 수정
- 현재 온도에 따른 카테고리 top 5 기능 추가
- 온도 리코일로 상태관리
> [Feat] #56, #118 게시글 및 페인 페이지 기능 추가

- src/app/feed/page.tsx
- src/app/mypage/page.tsx
- src/app/upload/page.tsx
- src/component/FeedCateDetail.tsx
- src/component/FeedCategory.tsx
- src/component/FeedContents.tsx
- src/component/FeedSearch.tsx
- src/component/FeedSort.tsx
- src/recoilAtom/FeedFulldata.ts
- src/style/FeedSort.scss
- src/style/GotoLogin.scss
- src/style/feedCategory.scss
> [Feat] 피드페이지 기능 구현 완료_디자인 작업 중 (#10)

- src/app/mypage/page.tsx
- src/app/upload/page.tsx
> [Fix]배포 오류 해결 (#10)

- src/component/LoginForm.tsx
- src/component/ProfileModalTest.tsx
- 로그인 method 수정
- 마이페이지 정보 수정 닉네임 / 비밀번호 / 이미지 구역별로 수정
> [fix] #43 마이페이지 정보 수정 구역별 설정 중

- src/app/feed/page.tsx
- src/app/page.tsx
- src/app/socialregister/page.tsx
- src/component/FeedCateDetail.tsx
- src/component/FeedContents.tsx
- src/component/FeedSearch.tsx
- src/component/FeedSort.tsx
- src/component/InputBar.tsx
- src/component/LoginForm.tsx
- src/component/MainWeather.tsx
- src/style/feedCateDetail.scss
- src/style/inputBar.scss
[Feat] 피드페이지 디자인 마무리, 소셜 로그인 페이지 구현 중 (#10)
> [Feat] 피드페이지 디자인 마무리, 소셜 로그인 페이지 구현 중 (#10)

- src/app/detail/page.tsx
- src/component/CommentIcon.tsx
- src/component/CommentTest.tsx
- src/component/ProfileModalTest.tsx
- src/style/modal.scss
- src/style/modal_comment.scss
- 댓글 데이터 업데이트 기능 완료
- 마이페이지 수정 모달 기능 수정 중
> [fix] #43 마이페이지, 댓글 수정 중

- src/app/socialregister/page.tsx
- src/component/MenuBar.tsx
[Feat] 소셜 로그인 토큰 받는 기능 제외 완성 (#148)
> [Feat] 소셜 로그인 토큰 받는 기능 제외 완성 (#148)

- src/app/upload/page.tsx
- src/component/BestCoordi.tsx
- src/component/BestItem.tsx
- src/style/best_main.scss
> [Feat] #118 메인 카테고리, 게시물 top5 불러오기 구현 완료

- src/app/register/page.tsx
- src/component/FeedContents.tsx
- src/component/FeedSort.tsx
- src/style/feedCategory.scss
[Fix] 날짜순 정렬 수정, 피드 페이지 css 수정, 소셜로그인 후 마이페이지
> [Fix] 날짜순 정렬 수정, 피드 페이지 css 수정, 소셜로그인 후 마이페이지

- src/component/MainWeather.tsx
- src/style/feedSearch.scss
- src/style/main.scss
> [Fix] 반응형 수정 Main #118
